name: medcalc
description: Aplicativo médico para cálculos clínicos e farmacológicos.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter



  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  string_similarity: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/bulas/medicamentos/
    - assets/medicamentos/
    - assets/data/inducoes.json
    - assets/data/condicoes/
